// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bmticpsxtrudxdljxnzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdGljcHN4dHJ1ZHhkbGp4bnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0ODUwMjEsImV4cCI6MjA4OTA2MTAyMX0.MpYCaU1RxBb-LID8HRAwPeHT6Su4ENPpgCQewcs8puw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
