// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lxliqyuqjzpqbiqajwth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4bGlxeXVxanpwcWJpcWFqd3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTk0NTAsImV4cCI6MjA2ODA3NTQ1MH0.K4x2TGjzh-1JVlKyF4kfKDJqSU9kOTj4dccQ7bMPAl0";

// Using 'any' for Database type until tables are created and types are generated
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
